name: .NET Core

on: 
  pull_request:
    branches:
      - master
      - Dev
    
    tags-ignore:
      - ignore        # ignore tag used to stop useless runs.
  
  push:
    tags:
      - run tests     # Used as a catch all in case I want to run tests on something that isn't a pull request.

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: dotnet build ".\RandomShopGen\RandomShopGen.sln" --configuration Debug
    - name: Run tests
      run: dotnet test ".\RandomShopGen\RandomShopGen.sln" --filter TestCategory!=LocalOnly
    - name: Discord success notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      if: success()
      with:
        args: ${{ github.event_name }} ${{ github.sha }} on branch ${{ github.ref }} passed build and test
    - name: Discord fail notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      if: failure()
      with:
        args: ${{ github.event_name }} ${{ github.sha }} on branch ${{ github.ref }} failed build and test
